modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"
[[mods]] 
modId="industrialupgrade"
version="3.3.1.11" #mandatory
displayName="Industrial Upgrade" #mandatory
credits=""
authors="Denfop"
description=''''''
[[dependencies.industrialupgrade]]
modId="forge" 
mandatory=true 
versionRange="[43,)" 
ordering="NONE"
side="BOTH"
[[dependencies.industrialupgrade]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"
#[[dependencies.industrialupgrade]]
#modId="lmft"
#mandatory=true
#versionRange="[0,)"
#ordering="NONE"
#side="BOTH"
